// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertEtudiantAjoute - Use 'AssertEtudiantAjouteExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertEtudiantAjoute()
        {
            #region Variable Declarations
            HtmlHyperlink uIMlavoisieyahoofrHyperlink = this.UIMSNCanadaCommuniquezWindow.UIIndexCodedUIAppDocument.UIMlavoisieyahoofrHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'm.lavoisie@yahoo.fr' link equals 'm.lavoisie@yahoo.fr '
            Assert.AreEqual(this.AssertEtudiantAjouteExpectedValues.UIMlavoisieyahoofrHyperlinkInnerText, uIMlavoisieyahoofrHyperlink.InnerText);
        }
        
        /// <summary>
        /// AssertValidationDate - Use 'AssertValidationDateExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertValidationDate()
        {
            #region Variable Declarations
            HtmlSpan uILavaleur25455nestpasPane = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UILavaleur25455nestpasPane;
            #endregion

            // Verify that the 'InnerText' property of 'La valeur « 25455 » n'est pas valide pou' pane equals 'Veuillez saisir une date valide'
            Assert.AreEqual(this.AssertValidationDateExpectedValues.UILavaleur25455nestpasPaneInnerText, uILavaleur25455nestpasPane.InnerText);
        }
        
        /// <summary>
        /// RecordedAjoutEtudiant_Invalide - Use 'RecordedAjoutEtudiant_InvalideParams' to pass parameters into this method.
        /// </summary>
        public void RecordedAjoutEtudiant_Invalide()
        {
            #region Variable Declarations
            HtmlHyperlink uINouvelEtudiantHyperlink = this.UIMSNCanadaCommuniquezWindow.UIIndexCodedUIAppDocument.UINouvelEtudiantHyperlink;
            HtmlEdit uINomEdit = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UINomEdit;
            HtmlEdit uIPrénomEdit = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UIPrénomEdit;
            HtmlEdit uIEmailEdit = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UIEmailEdit;
            HtmlRadioButton uISexeRadioButtonH = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UISexeRadioButtonH;
            HtmlEdit uIDatedeNaissanceEdit = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UIDatedeNaissanceEdit;
            HtmlInputButton uIEnregistrerButton = this.UIMSNCanadaCommuniquezWindow.UICreateCodedUIAppDocument.UIEnregistrerButton;
            #endregion

            // Click 'Nouvel Etudiant' link
            Mouse.Click(uINouvelEtudiantHyperlink, new Point(60, 9));

            // Type 'Papin' in 'Nom' text box
            uINomEdit.Text = this.RecordedAjoutEtudiant_InvalideParams.UINomEditText;

            // Type '{Tab}' in 'Nom' text box
            Keyboard.SendKeys(uINomEdit, this.RecordedAjoutEtudiant_InvalideParams.UINomEditSendKeys, ModifierKeys.None);

            // Type 'Jean' in 'Prénom' text box
            uIPrénomEdit.Text = this.RecordedAjoutEtudiant_InvalideParams.UIPrénomEditText;

            // Type '{Tab}' in 'Prénom' text box
            Keyboard.SendKeys(uIPrénomEdit, this.RecordedAjoutEtudiant_InvalideParams.UIPrénomEditSendKeys, ModifierKeys.None);

            // Type 'j.papin' in 'Email' text box
            uIEmailEdit.Text = this.RecordedAjoutEtudiant_InvalideParams.UIEmailEditText;

            // Type 'Alt, Control + 2' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.RecordedAjoutEtudiant_InvalideParams.UIEmailEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'j.papin@gmail.com' in 'Email' text box
            uIEmailEdit.Text = this.RecordedAjoutEtudiant_InvalideParams.UIEmailEditText1;

            // Select 'Sexe' radio button
            uISexeRadioButtonH.Selected = this.RecordedAjoutEtudiant_InvalideParams.UISexeRadioButtonHSelected;

            // Type '{Tab}' in 'Sexe' radio button
            Keyboard.SendKeys(uISexeRadioButtonH, this.RecordedAjoutEtudiant_InvalideParams.UISexeRadioButtonHSendKeys, ModifierKeys.None);

            // Type '25455' in 'Date de Naissance' text box
            uIDatedeNaissanceEdit.Text = this.RecordedAjoutEtudiant_InvalideParams.UIDatedeNaissanceEditText;

            // Click 'Enregistrer' button
            Mouse.Click(uIEnregistrerButton, new Point(33, 12));
        }
        
        /// <summary>
        /// RecordedLaunchApp - Use 'RecordedLaunchAppParams' to pass parameters into this method.
        /// </summary>
        public void RecordedLaunchApp()
        {
            #region Variable Declarations
            BrowserWindow uIMSNCanadaCommuniquezWindow = this.UIMSNCanadaCommuniquezWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            this.UIMSNCanadaCommuniquezWindow.LaunchUrl(new System.Uri(this.RecordedLaunchAppParams.UIMSNCanadaCommuniquezWindowUrl));

            // Go to web page 'http://localhost:64446/'
            uIMSNCanadaCommuniquezWindow.NavigateToUrl(new System.Uri(this.RecordedLaunchAppParams.UIMSNCanadaCommuniquezWindowUrl1));
        }
        
        #region Properties
        public virtual AssertEtudiantAjouteExpectedValues AssertEtudiantAjouteExpectedValues
        {
            get
            {
                if ((this.mAssertEtudiantAjouteExpectedValues == null))
                {
                    this.mAssertEtudiantAjouteExpectedValues = new AssertEtudiantAjouteExpectedValues();
                }
                return this.mAssertEtudiantAjouteExpectedValues;
            }
        }
        
        public virtual AssertValidationDateExpectedValues AssertValidationDateExpectedValues
        {
            get
            {
                if ((this.mAssertValidationDateExpectedValues == null))
                {
                    this.mAssertValidationDateExpectedValues = new AssertValidationDateExpectedValues();
                }
                return this.mAssertValidationDateExpectedValues;
            }
        }
        
        public virtual RecordedAjoutEtudiant_InvalideParams RecordedAjoutEtudiant_InvalideParams
        {
            get
            {
                if ((this.mRecordedAjoutEtudiant_InvalideParams == null))
                {
                    this.mRecordedAjoutEtudiant_InvalideParams = new RecordedAjoutEtudiant_InvalideParams();
                }
                return this.mRecordedAjoutEtudiant_InvalideParams;
            }
        }
        
        public virtual RecordedLaunchAppParams RecordedLaunchAppParams
        {
            get
            {
                if ((this.mRecordedLaunchAppParams == null))
                {
                    this.mRecordedLaunchAppParams = new RecordedLaunchAppParams();
                }
                return this.mRecordedLaunchAppParams;
            }
        }
        
        public UIMSNCanadaCommuniquezWindow UIMSNCanadaCommuniquezWindow
        {
            get
            {
                if ((this.mUIMSNCanadaCommuniquezWindow == null))
                {
                    this.mUIMSNCanadaCommuniquezWindow = new UIMSNCanadaCommuniquezWindow();
                }
                return this.mUIMSNCanadaCommuniquezWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertEtudiantAjouteExpectedValues mAssertEtudiantAjouteExpectedValues;
        
        private AssertValidationDateExpectedValues mAssertValidationDateExpectedValues;
        
        private RecordedAjoutEtudiant_InvalideParams mRecordedAjoutEtudiant_InvalideParams;
        
        private RecordedLaunchAppParams mRecordedLaunchAppParams;
        
        private UIMSNCanadaCommuniquezWindow mUIMSNCanadaCommuniquezWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertEtudiantAjoute'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class AssertEtudiantAjouteExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'm.lavoisie@yahoo.fr' link equals 'm.lavoisie@yahoo.fr '
        /// </summary>
        public string UIMlavoisieyahoofrHyperlinkInnerText = "m.lavoisie@yahoo.fr ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertValidationDate'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class AssertValidationDateExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'La valeur « 25455 » n'est pas valide pou' pane equals 'Veuillez saisir une date valide'
        /// </summary>
        public string UILavaleur25455nestpasPaneInnerText = "Veuillez saisir une date valide";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedAjoutEtudiant_Invalide'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class RecordedAjoutEtudiant_InvalideParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Papin' in 'Nom' text box
        /// </summary>
        public string UINomEditText = "Papin";
        
        /// <summary>
        /// Type '{Tab}' in 'Nom' text box
        /// </summary>
        public string UINomEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Jean' in 'Prénom' text box
        /// </summary>
        public string UIPrénomEditText = "Jean";
        
        /// <summary>
        /// Type '{Tab}' in 'Prénom' text box
        /// </summary>
        public string UIPrénomEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'j.papin' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "j.papin";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "2";
        
        /// <summary>
        /// Type 'j.papin@gmail.com' in 'Email' text box
        /// </summary>
        public string UIEmailEditText1 = "j.papin@gmail.com";
        
        /// <summary>
        /// Select 'Sexe' radio button
        /// </summary>
        public bool UISexeRadioButtonHSelected = true;
        
        /// <summary>
        /// Type '{Tab}' in 'Sexe' radio button
        /// </summary>
        public string UISexeRadioButtonHSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '25455' in 'Date de Naissance' text box
        /// </summary>
        public string UIDatedeNaissanceEditText = "25455";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedLaunchApp'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class RecordedLaunchAppParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string UIMSNCanadaCommuniquezWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        
        /// <summary>
        /// Go to web page 'http://localhost:64446/'
        /// </summary>
        public string UIMSNCanadaCommuniquezWindowUrl1 = "http://localhost:64446/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class UIMSNCanadaCommuniquezWindow : BrowserWindow
    {
        
        public UIMSNCanadaCommuniquezWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Canada - Communiquez grâce à Hotmail, Outlook, Skype. Actualités, horoscope, " +
                "météo, photos,";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Canada - Communiquez grâce à Hotmail, Outlook, Skype. Actualités, horoscope, " +
                    "météo, photos,");
            this.WindowTitles.Add("Index - Coded UI App");
            this.WindowTitles.Add("Create - Coded UI App");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIIndexCodedUIAppDocument UIIndexCodedUIAppDocument
        {
            get
            {
                if ((this.mUIIndexCodedUIAppDocument == null))
                {
                    this.mUIIndexCodedUIAppDocument = new UIIndexCodedUIAppDocument(this);
                }
                return this.mUIIndexCodedUIAppDocument;
            }
        }
        
        public UICreateCodedUIAppDocument UICreateCodedUIAppDocument
        {
            get
            {
                if ((this.mUICreateCodedUIAppDocument == null))
                {
                    this.mUICreateCodedUIAppDocument = new UICreateCodedUIAppDocument(this);
                }
                return this.mUICreateCodedUIAppDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIIndexCodedUIAppDocument mUIIndexCodedUIAppDocument;
        
        private UICreateCodedUIAppDocument mUICreateCodedUIAppDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class UIIndexCodedUIAppDocument : HtmlDocument
    {
        
        public UIIndexCodedUIAppDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Coded UI App";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:64446/";
            this.WindowTitles.Add("Index - Coded UI App");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UINouvelEtudiantHyperlink
        {
            get
            {
                if ((this.mUINouvelEtudiantHyperlink == null))
                {
                    this.mUINouvelEtudiantHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUINouvelEtudiantHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUINouvelEtudiantHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUINouvelEtudiantHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUINouvelEtudiantHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Nouvel Etudiant";
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Etudiants/Create";
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:64446/Etudiants/Create";
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Etudiants/Create\"";
                    this.mUINouvelEtudiantHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUINouvelEtudiantHyperlink.WindowTitles.Add("Index - Coded UI App");
                    #endregion
                }
                return this.mUINouvelEtudiantHyperlink;
            }
        }
        
        public HtmlHyperlink UIMlavoisieyahoofrHyperlink
        {
            get
            {
                if ((this.mUIMlavoisieyahoofrHyperlink == null))
                {
                    this.mUIMlavoisieyahoofrHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIMlavoisieyahoofrHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIMlavoisieyahoofrHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIMlavoisieyahoofrHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIMlavoisieyahoofrHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "m.lavoisie@yahoo.fr ";
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "mailto:m.lavoisie@yahoo.fr";
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"mailto:m.lavoisie@yahoo.fr        ";
                    this.mUIMlavoisieyahoofrHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIMlavoisieyahoofrHyperlink.WindowTitles.Add("Index - Coded UI App");
                    #endregion
                }
                return this.mUIMlavoisieyahoofrHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUINouvelEtudiantHyperlink;
        
        private HtmlHyperlink mUIMlavoisieyahoofrHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class UICreateCodedUIAppDocument : HtmlDocument
    {
        
        public UICreateCodedUIAppDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - Coded UI App";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Etudiants/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:64446/Etudiants/Create";
            this.WindowTitles.Add("Create - Coded UI App");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINomEdit
        {
            get
            {
                if ((this.mUINomEdit == null))
                {
                    this.mUINomEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINomEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Nom";
                    this.mUINomEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Nom";
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nom";
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Nom\" class=\"form-control text-box ";
                    this.mUINomEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUINomEdit.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUINomEdit;
            }
        }
        
        public HtmlEdit UIPrénomEdit
        {
            get
            {
                if ((this.mUIPrénomEdit == null))
                {
                    this.mUIPrénomEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPrénomEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Prenom";
                    this.mUIPrénomEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Prenom";
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Prénom";
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Prenom\" class=\"form-control text-b";
                    this.mUIPrénomEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPrénomEdit.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIPrénomEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control text-bo";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIEmailEdit.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlRadioButton UISexeRadioButtonH
        {
            get
            {
                if ((this.mUISexeRadioButtonH == null))
                {
                    this.mUISexeRadioButtonH = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUISexeRadioButtonH.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "Sexe";
                    this.mUISexeRadioButtonH.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "Sexe";
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "Homme";
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = "Sexe";
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "2";
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.Class] = null;
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"Sexe\" id=\"Sexe\" type=\"radio\" value";
                    this.mUISexeRadioButtonH.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "5";
                    this.mUISexeRadioButtonH.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUISexeRadioButtonH;
            }
        }
        
        public HtmlEdit UIDatedeNaissanceEdit
        {
            get
            {
                if ((this.mUIDatedeNaissanceEdit == null))
                {
                    this.mUIDatedeNaissanceEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDatedeNaissanceEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DateNais";
                    this.mUIDatedeNaissanceEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DateNais";
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Date de Naissance";
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line hasDatepicker";
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DateNais\" class=\"form-control text";
                    this.mUIDatedeNaissanceEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIDatedeNaissanceEdit.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIDatedeNaissanceEdit;
            }
        }
        
        public UIUidatepickerdivPane UIUidatepickerdivPane
        {
            get
            {
                if ((this.mUIUidatepickerdivPane == null))
                {
                    this.mUIUidatepickerdivPane = new UIUidatepickerdivPane(this);
                }
                return this.mUIUidatepickerdivPane;
            }
        }
        
        public HtmlDiv UISexeHommeFemmePane
        {
            get
            {
                if ((this.mUISexeHommeFemmePane == null))
                {
                    this.mUISexeHommeFemmePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISexeHommeFemmePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUISexeHommeFemmePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISexeHommeFemmePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sexe \r\n Homme  Femme  ";
                    this.mUISexeHommeFemmePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISexeHommeFemmePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "form-group";
                    this.mUISexeHommeFemmePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"form-group\"";
                    this.mUISexeHommeFemmePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
                    this.mUISexeHommeFemmePane.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUISexeHommeFemmePane;
            }
        }
        
        public HtmlInputButton UIEnregistrerButton
        {
            get
            {
                if ((this.mUIEnregistrerButton == null))
                {
                    this.mUIEnregistrerButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIEnregistrerButton.SearchProperties[HtmlButton.PropertyNames.Id] = "Enregistrer";
                    this.mUIEnregistrerButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIEnregistrerButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Enregistrer";
                    this.mUIEnregistrerButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIEnregistrerButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIEnregistrerButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIEnregistrerButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"Enregistrer\"";
                    this.mUIEnregistrerButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "8";
                    this.mUIEnregistrerButton.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIEnregistrerButton;
            }
        }
        
        public HtmlSpan UILavaleur25455nestpasPane
        {
            get
            {
                if ((this.mUILavaleur25455nestpasPane == null))
                {
                    this.mUILavaleur25455nestpasPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUILavaleur25455nestpasPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILavaleur25455nestpasPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILavaleur25455nestpasPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "La valeur « 25455 » n\'est pas valide pou";
                    this.mUILavaleur25455nestpasPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILavaleur25455nestpasPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "field-validation-error text-danger";
                    this.mUILavaleur25455nestpasPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"field-validation-error text-danger\" data-valmsg-replace=\"true\" data-valmsg" +
                        "-for=\"DateNais\"";
                    this.mUILavaleur25455nestpasPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUILavaleur25455nestpasPane.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUILavaleur25455nestpasPane;
            }
        }
        
        public HtmlRadioButton UISexeRadioButtonF
        {
            get
            {
                if ((this.mUISexeRadioButtonF == null))
                {
                    this.mUISexeRadioButtonF = new HtmlRadioButton(this);
                    #region Search Criteria
                    this.mUISexeRadioButtonF.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "Sexe";
                    this.mUISexeRadioButtonF.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "Sexe";
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "Femme";
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = "Sexe";
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "2";
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.Class] = null;
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"Sexe\" id=\"Sexe\" type=\"radio\" value";
                    this.mUISexeRadioButtonF.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "6";
                    this.mUISexeRadioButtonF.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUISexeRadioButtonF;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINomEdit;
        
        private HtmlEdit mUIPrénomEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlRadioButton mUISexeRadioButtonH;
        
        private HtmlEdit mUIDatedeNaissanceEdit;
        
        private UIUidatepickerdivPane mUIUidatepickerdivPane;
        
        private HtmlDiv mUISexeHommeFemmePane;
        
        private HtmlInputButton mUIEnregistrerButton;
        
        private HtmlSpan mUILavaleur25455nestpasPane;
        
        private HtmlRadioButton mUISexeRadioButtonF;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class UIUidatepickerdivPane : HtmlDiv
    {
        
        public UIUidatepickerdivPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ui-datepicker-div";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Prev\r\n\r\nNext\r\n\r\nJanFebMarAprMayJunJulAug";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" +
                "\" id=\"ui-datepicker-div\" style=\"left: 58px; top: 250.36px; display: block; posit" +
                "ion: absolute; z-index: 1;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "16";
            this.WindowTitles.Add("Create - Coded UI App");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem22Hyperlink
        {
            get
            {
                if ((this.mUIItem22Hyperlink == null))
                {
                    this.mUIItem22Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem22Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem22Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem22Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem22Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "22";
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Etudiants/Create";
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:64446/Etudiants/Create#";
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mUIItem22Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "24";
                    this.mUIItem22Hyperlink.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIItem22Hyperlink;
            }
        }
        
        public HtmlHyperlink UIItem16Hyperlink
        {
            get
            {
                if ((this.mUIItem16Hyperlink == null))
                {
                    this.mUIItem16Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem16Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem16Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem16Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem16Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "16";
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Etudiants/Create";
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:64446/Etudiants/Create#";
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mUIItem16Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mUIItem16Hyperlink.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIItem16Hyperlink;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIItem9Hyperlink
        {
            get
            {
                if ((this.mUIItem9Hyperlink == null))
                {
                    this.mUIItem9Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem9Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem9Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem9Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem9Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "9";
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Etudiants/Create";
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:64446/Etudiants/Create#";
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mUIItem9Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "11";
                    this.mUIItem9Hyperlink.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIItem9Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem22Hyperlink;
        
        private HtmlHyperlink mUIItem16Hyperlink;
        
        private UIItemTable mUIItemTable;
        
        private HtmlHyperlink mUIItem9Hyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.25420.1")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Su\r\n\r\nMo\r\n\r\nTu\r\n\r\nWe\r\n\r\nTh\r\n\r\nFr\r\n\r\nSa\r\n";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"ui-datepicker-calendar\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "6";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "7";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "ui-datepicker-calendar";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Create - Coded UI App");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItem16Cell
        {
            get
            {
                if ((this.mUIItem16Cell == null))
                {
                    this.mUIItem16Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem16Cell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem16Cell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem16Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem16Cell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "16";
                    this.mUIItem16Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\" \" data-event=\"click\" data-handler=\"selectDay\" data-year=\"2016\" data-month" +
                        "=\"7\"";
                    this.mUIItem16Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "3";
                    this.mUIItem16Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem16Cell.FilterProperties[HtmlCell.PropertyNames.Class] = " ";
                    this.mUIItem16Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "17";
                    this.mUIItem16Cell.WindowTitles.Add("Create - Coded UI App");
                    #endregion
                }
                return this.mUIItem16Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItem16Cell;
        #endregion
    }
}
